export const CREATE_G_TASK = "G_TASK/CREATE"
export const GET_G_TASKS = "G_TASK/GET_ALL"
export const DELETE_G_TASK = "G_TASK/DELETE"
export const EDIT_G_TASK = "G_TASK/EDIT"
export const SET_G_TASKS = "G_TASKS/SET_TASKS"
export const SET_All_GTASKS = "G_TASKS/SET_All"
    // export const ADD_TASK_ID = "G_TASK/ADD_TASK_ID"