export const CREATE_CALENDAR_EVENT = "CALENDAR/CREATE_EVENT"
export const GET_ALLEVENTS = "CALENDAR/GET_ALLEVENTS"
export const DELETE_EVENT = "CALENDAR/DELETE_EVENT"
export const EDIT_EVENT = "CALENDAR/EDIT_EVENT"